name: 'Setup pnpm'
description: 'Setup pnpm and Node.js with caching'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
  pnpm-version:
    description: 'pnpm version to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
